### ISSUE TITLE
How to bind event handlers and listeners for JavaFx application ?

### ISSUE THREAD

**Issue by BaskiR** [guigarage/jwrap#1]
Hi Hendrik,

Thanks for your sample code.

Actually my problem is same as u done in the jwrap project code.

I want create one application with javafx with fxml file instead of java file page design.

I was followed the same procedure to call the event listeners whenever user clicked on the button.

But in my project , registered event listener is not triggered . This is actual problem.

Can your help me please ?

Thanks

**Comment by hendrikebbers** [comment]
Hi,
if you simply want to use JavaFX and FXML maybe DataFX is a better solution since it's provides more features. See http://www.guigarage.com/category/datafx/ for more information.
JWrap is cool if you have an app that uses a mix like Swing and JavaFX or if you want to migrate from Swing to JavaFX. 
If you want to use Wrap I need more information about your problem :)

If you have additional questions please ask me :) Here the best place for questions is a comment in my blog http://www.guigarage.com 
By doing so the question and answer will help other developers with the same problem.
